### ISSUE TITLE
on grunt task (build) vendor file come out empty

### ISSUE THREAD

**Issue by talmog** [bassjobsen/generator-foundation6#1]
the vendor file is created but empty... help please!

**Comment by bassjobsen** [comment]
i found that `grunt serve` runs but the default task fails:
Gruntfile.js
  193:14  error  Expected indentation of 14 space characters but found 13  indent
  194:14  error  Expected indentation of 14 space characters but found 13  indent
  195:14  error  Expected indentation of 14 space characters but found 13  indent

✖ 3 problems (3 errors, 0 warnings)
try `grunt --force`, i will fix the linting error soon

**Comment by talmog** [comment]
yes, I just added a space for each of these lines to solve that, but still the vendor file is created empty...

**Comment by bassjobsen** [comment]
okay could you give me some more details? Which file exactly and what should be in this file?
