### ISSUE TITLE
browser-sync-client.2.10.0.js not found

### ISSUE THREAD

**Issue by aravasio** [bassjobsen/generator-foundation6#2]
When I try to use this generator, the index.html ends up reporting the following:

> http://localhost:9000/browser-sync/browser-sync-client.2.10.0.js
> **Failed to load resource: the server responded with a status of 404 (Not Found)**

I can certainly remove the

```
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.10.0.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

fragment from app/index.html, but I don't think this should be the case. Is it proper to report it as an issue?

Thanks

**Comment by bassjobsen** [comment]
@aravasio thanks for posting your issue. You're right about that i removed the browser-sync snippet.
